-- Copy and paste this into the Supabase SQL Editor
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS address_complement TEXT,
ADD COLUMN IF NOT EXISTS postal_code TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS phone_mobile TEXT,
ADD COLUMN IF NOT EXISTS phone_fixed TEXT,
ADD COLUMN IF NOT EXISTS is_profile_completed BOOLEAN DEFAULT false;
